version: '3.0'

services:
  leone:
    image: rahulbaradol/leones-arc
    ports:
      - "8080:8080"
    container_name: leone
    restart: always
    networks:
      - mynetwork

  node1:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5000
      SERVER_IP: node1
    ports:
      - "5000:5000"
    container_name: node1
    restart: always
    networks:
      - mynetwork

  node2:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5001
      SERVER_IP: node2
    ports:
      - "5001:5001"
    container_name: node2
    restart: always
    networks:
      - mynetwork

  node3:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5002
      SERVER_IP: node3
    ports:
      - "5002:5002"
    container_name: node3
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge