version: '3.0'

services:
  leone:
    image: rahulbaradol/leones-arc
    ports:
      - "8080:8080"
    container_name: leone
    restart: always
    networks:
      - mynetwork

  node1:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5000
      SERVER_IP: 10.0.0.1
    ports:
      - "5000:5000"
    container_name: node1
    restart: always
    networks:
      mynetwork:
        ipv4_address: 10.0.0.1

  node2:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5001
      SERVER_IP: 10.0.0.2
    ports:
      - "5001:5001"
    container_name: node2
    restart: always
    networks:
      mynetwork:
        ipv4_address: 10.0.0.2

  node3:
    image: rahulbaradol/leones-arc-node
    environment:
      LOAD_BALANCER_URL: http://leone:8080/register
      SERVER_PORT: 5002
      SERVER_IP: 10.0.0.3
    ports:
      - "5002:5002"
    container_name: node3
    restart: always
    networks:
      mynetwork:
        ipv4_address: 10.0.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.6